censo:
    resource: "@CensoBundle/Controller/"
    type:     annotation
    prefix:   /
    
login:
  pattern: /login
  defaults: {_controller: CensoBundle:Seguridad:login}

login_check:
  pattern: /login_check

logout:
  pattern: /logout