security:
    encoders:
        Censo\CensoBundle\Entity\Usuarios:
            algorithm: sha512
            encode-as-base64: true
            iterations: 10

    providers:
        user_db:
            entity: { class: CensoBundle:Usuarios }

    role_hierarchy:        
        ROLE_USER: ROLE_CCOMUNAL
        ROLE_ADMIN: ROLE_COMUNA
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]
        
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/login$
            security: false

        secured_area:
            pattern:    ^/
            form_login:
                login_path: /login
                check_path: /login_check
                failure_path: /login
            logout:
                path: /logout
                target: /login
            anonymous: ~

    access_control:
      - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
      - { path: ^/usuarios, roles:  ROLE_SUPER_ADMIN}
      - { path: ^/habitantes, roles:  ROLE_SUPER_ADMIN}
      - { path: ^/plagas, roles:  ROLE_SUPER_ADMIN}
#      - { path: ^/principal/*, roles:  ROLE_SUPER_ADMIN}
      