<?php

namespace Proxies\__CG__\Censo\CensoBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Familias extends \Censo\CensoBundle\Entity\Familias implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Censo\\CensoBundle\\Entity\\Familias' . "\0" . 'id', '' . "\0" . 'Censo\\CensoBundle\\Entity\\Familias' . "\0" . 'apellidos', '' . "\0" . 'Censo\\CensoBundle\\Entity\\Familias' . "\0" . 'telefonoLocal', '' . "\0" . 'Censo\\CensoBundle\\Entity\\Familias' . "\0" . 'telefonoMovil', '' . "\0" . 'Censo\\CensoBundle\\Entity\\Familias' . "\0" . 'sector', '' . "\0" . 'Censo\\CensoBundle\\Entity\\Familias' . "\0" . 'nombresComunidad', '' . "\0" . 'Censo\\CensoBundle\\Entity\\Familias' . "\0" . 'habitantes', '' . "\0" . 'Censo\\CensoBundle\\Entity\\Familias' . "\0" . 'usuarios');
        }

        return array('__isInitialized__', '' . "\0" . 'Censo\\CensoBundle\\Entity\\Familias' . "\0" . 'id', '' . "\0" . 'Censo\\CensoBundle\\Entity\\Familias' . "\0" . 'apellidos', '' . "\0" . 'Censo\\CensoBundle\\Entity\\Familias' . "\0" . 'telefonoLocal', '' . "\0" . 'Censo\\CensoBundle\\Entity\\Familias' . "\0" . 'telefonoMovil', '' . "\0" . 'Censo\\CensoBundle\\Entity\\Familias' . "\0" . 'sector', '' . "\0" . 'Censo\\CensoBundle\\Entity\\Familias' . "\0" . 'nombresComunidad', '' . "\0" . 'Censo\\CensoBundle\\Entity\\Familias' . "\0" . 'habitantes', '' . "\0" . 'Censo\\CensoBundle\\Entity\\Familias' . "\0" . 'usuarios');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Familias $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setApellidos($apellidos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApellidos', array($apellidos));

        return parent::setApellidos($apellidos);
    }

    /**
     * {@inheritDoc}
     */
    public function getApellidos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApellidos', array());

        return parent::getApellidos();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefonoLocal($telefonoLocal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefonoLocal', array($telefonoLocal));

        return parent::setTelefonoLocal($telefonoLocal);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefonoLocal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefonoLocal', array());

        return parent::getTelefonoLocal();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefonoMovil($telefonoMovil)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefonoMovil', array($telefonoMovil));

        return parent::setTelefonoMovil($telefonoMovil);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefonoMovil()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefonoMovil', array());

        return parent::getTelefonoMovil();
    }

    /**
     * {@inheritDoc}
     */
    public function setSector($sector)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSector', array($sector));

        return parent::setSector($sector);
    }

    /**
     * {@inheritDoc}
     */
    public function getSector()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSector', array());

        return parent::getSector();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombresComunidad($nombresComunidad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombresComunidad', array($nombresComunidad));

        return parent::setNombresComunidad($nombresComunidad);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombresComunidad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombresComunidad', array());

        return parent::getNombresComunidad();
    }

    /**
     * {@inheritDoc}
     */
    public function setHabitantes(\Censo\CensoBundle\Entity\Habitantes $habitantes = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHabitantes', array($habitantes));

        return parent::setHabitantes($habitantes);
    }

    /**
     * {@inheritDoc}
     */
    public function getHabitantes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHabitantes', array());

        return parent::getHabitantes();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuarios(\Censo\CensoBundle\Entity\Usuarios $usuarios = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuarios', array($usuarios));

        return parent::setUsuarios($usuarios);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuarios()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuarios', array());

        return parent::getUsuarios();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

}
